### ISSUE TITLE
Extension doesn't work after 0.18.0 update

### ISSUE THREAD

**Issue by definitio** [esphome/esphome-vscode#30]
```
[2021-06-27 19:09:15.387] [exthost] [error] Activating extension ESPHome.esphome-vscode failed due to an error:
[2021-06-27 19:09:15.387] [exthost] [error] Error: Cannot find module '/home/username/.vscode-oss/extensions/esphome.esphome-vscode-0.18.0/client/out/extension'
Require stack:
- /usr/lib/code/out/vs/loader.js
- /usr/lib/code/out/bootstrap-amd.js
- /usr/lib/code/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
	at Module._load (internal/modules/cjs/loader.js:732:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.s._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27814)
	at Function.S._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:24531)
	at Function.a._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:58820)
	at Module.require (internal/modules/cjs/loader.js:959:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/usr/lib/code/out/vs/loader.js:5:101)
	at d._loadCommonJSModule (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:25940)
	at d._doActivateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:12457)
	at d._activateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:92:11516)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
```

**Comment by glmnet** [comment]
Should be fixed now in v19, something went wrong creating the package

**Comment by definitio** [comment]
Thanks!
